version: "3"
services:
  databases:
    build:
      context: ./
      dockerfile: Dockerfile.maria
    restart: always
    ports:
      - 3306:3306
    networks:
      - programming

  api:
    build:
      context: ./
      dockerfile: Dockerfile.express
    depends_on:
      - databases
    networks:
      - programming
    ports:
      - 8080:3000
    restart: always
    volumes:
      - "./src:/usr/src/app/src"
networks:
  programming:
    driver: bridge
