version: '3'
services:
  databases:
    build:
      context: ./
      dockerfile: Dockerfile.maria
    restart: always
    ports:
      - 3306:3306
    networks:
      - programming
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      restart_policy:
        condition: on-failure

  api:
    build:
      context: ./
      dockerfile: Dockerfile.express
    depends_on:
      - databases
    networks:
      - programming
    ports:
      - 80:3000
    restart: always
    volumes:
      - './src:/usr/src/app/src'
      - './index.js:/usr/src/app/index.js'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure

networks:
  programming:
    driver: bridge
